# Generated by Django 5.0.6 on 2024-06-18 22:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anon_User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=60, verbose_name='title')),
                ('image', models.CharField(default='', max_length=20, verbose_name='image')),
                ('description', models.CharField(default='', max_length=250, verbose_name='description')),
                ('github_link', models.CharField(default='', max_length=100, verbose_name='github_link')),
                ('website_link', models.CharField(default='', max_length=100, verbose_name='website_link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0, verbose_name='likes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userPosts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'base_post',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userLikes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postLikes', to='base.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'likes',
                'db_table': 'base_like',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('content', models.CharField(default='', max_length=250, verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0, verbose_name='likes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userComments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeComments', to='base.like', verbose_name='like')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postComments', to='base.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'base_comment',
            },
        ),
    ]
