# Generated by Django 5.0.6 on 2024-06-18 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anon_user',
            options={'verbose_name': 'anon_user', 'verbose_name_plural': 'anon_users'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.AlterModelTable(
            name='anon_user',
            table='base_anon_user',
        ),
    ]
