# Generated by Django 5.0.6 on 2024-06-20 18:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_comment_likes_comment_anon_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='PostLike',
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name': 'post_like', 'verbose_name_plural': 'post_likes'},
        ),
        migrations.AlterModelTable(
            name='postlike',
            table='base_post_like',
        ),
    ]
