# Generated by Django 5.0.6 on 2024-06-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_like_postlike_alter_postlike_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anon_user',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=250, verbose_name='content'),
        ),
    ]
