# Generated by Django 5.0.6 on 2024-07-11 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_post_website_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hearts',
            field=models.PositiveIntegerField(default=0, verbose_name='hearts'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='', max_length=20, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='PostHeart',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anon_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anon_userHearts', to='base.anon_user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postHearts', to='base.post', verbose_name='post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userHearts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'post_heart',
                'verbose_name_plural': 'post_hearts',
                'db_table': 'base_post_heart',
            },
        ),
    ]
