# Generated by Django 5.0.6 on 2024-07-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_post_hearts_post_status_postheart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=450, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='github_link',
            field=models.CharField(default='', max_length=200, verbose_name='github_link'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(default='', max_length=350, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(default='', max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=90, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='website_link',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='website_link'),
        ),
    ]
